server:
  port: 8021
spring:
  application:
    name: abbitmq-provider
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    publisher-returns: true
#    这边听说新版要配置这个才能提示成功回调的消息
    publisher-confirm-type: correlated

