server:
  port: 8021
spring:
  application:
    name: abbitmq-provider
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /
#    是否开启交换机发送成功回调消息
    publisher-returns: true
#    这边听说新版要配置这个才能提示成功回调的消息
    publisher-confirm-type: correlated
    listener:
      simple:
        retry:
          # 开启自动重试,这边的重试指的是手动消息确认没有确认的重试次数
          enabled: true
          # 最大重试次数
          max-attempts: 5
          # 重试时间间隔
          initial-interval: 3000
#          这边是开启手动消息确认的功能
        acknowledge-mode: manual
        #        这边是配置一次拉取多少条，可以实现限流（削峰填谷）:10
        prefetch: 10
